### ISSUE TITLE
Unhandled `reconnect_ins` in `FlowerServiceRunnable`.

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/dyn_flower_android_drf#26]
At 961cce7b5cab496e95666fcdbbc8d1724e73042b

```log
2023-07-12 12:59:25.070 25838-19943 Flower Service Runnable org.eu.fedcampus.benchmark           E  java.lang.Error: Unknown client message # flwr.android_client.ServerMessage@1a1bf6a
                                                                                                    reconnect_ins {
                                                                                                      seconds: 0
                                                                                                    }.
                                                                                                    	at org.eu.fedcampus.train.FlowerServiceRunnable.handleMessage(FlowerServiceRunnable.kt:68)
                                                                                                    	at org.eu.fedcampus.train.FlowerServiceRunnable$requestObserver$1.onNext(FlowerServiceRunnable.kt:43)
                                                                                                    	at org.eu.fedcampus.train.FlowerServiceRunnable$requestObserver$1.onNext(FlowerServiceRunnable.kt:41)
                                                                                                    	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:478)
                                                                                                    	at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:473)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:660)
                                                                                                    	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:647)
                                                                                                    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
                                                                                                    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:933)
```

**Comment by SichangHe** [comment]
Fixed by 49a8bd3726996caa0a4a99bfc6c6079ee6aaeb3c.
