### ISSUE TITLE
Flower server had division by zero and crashed

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/dyn_flower_android_drf#3]
Two physical Android device joined the training. One joined first, and the second one joined after the first round.

```sh
$ python3 manage.py runserver 0.0.0.0:8000
Watching for file changes with StatReloader
Performing system checks...

/opt/homebrew/lib/python3.11/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.0.1) or chardet (None)/charset_normalizer (2.1.1) doesn't match a supported version!
  warnings.warn(
System check identified no issues (0 silenced).
May 24, 2023 - 06:51:01
Django version 4.2.1, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[24/May/2023 06:53:26] "GET /train/get_advertised HTTP/1.1" 200 270
[24/May/2023 06:53:26] "GET /static/CIFAR10_model/inference.tflite HTTP/1.1" 200 4200
[24/May/2023 06:53:26] "GET /static/CIFAR10_model/optimizer.tflite HTTP/1.1" 200 3932
[24/May/2023 06:53:26] "GET /static/CIFAR10_model/bottleneck.tflite HTTP/1.1" 200 532
[24/May/2023 06:53:26] "GET /static/CIFAR10_model/train_head.tflite HTTP/1.1" 200 16012
[24/May/2023 06:53:26] "GET /static/CIFAR10_model/initialize.tflite HTTP/1.1" 200 825124
Starting Flower server.
Started flower server for model TFLiteModel object (1)
[24/May/2023 06:53:27] "POST /train/server HTTP/1.1" 200 28
INFO flwr 2023-05-24 06:53:27,496 | app.py:148 | Starting Flower server, config: ServerConfig(num_rounds=10, round_timeout=None)
INFO flwr 2023-05-24 06:53:27,506 | app.py:168 | Flower ECE: gRPC server running (10 rounds), SSL is disabled
INFO flwr 2023-05-24 06:53:27,507 | server.py:86 | Initializing global parameters
initialize_parameters: parameters shape is [1800, 24, 9600, 64, 768000, 480, 40320, 336, 3360, 40].
INFO flwr 2023-05-24 06:53:27,507 | server.py:269 | Using initial parameters provided by strategy
INFO flwr 2023-05-24 06:53:27,507 | server.py:88 | Evaluating initial parameters
INFO flwr 2023-05-24 06:53:27,507 | server.py:101 | FL starting
configure_fit: 1 server round, parameters shape is [1800, 24, 9600, 64, 768000, 480, 40320, 336, 3360, 40].
[24/May/2023 06:54:04] "GET /train/get_advertised HTTP/1.1" 200 270
[24/May/2023 06:54:04] "GET /static/CIFAR10_model/train_head.tflite HTTP/1.1" 200 16012
[24/May/2023 06:54:05] "GET /static/CIFAR10_model/inference.tflite HTTP/1.1" 200 4200
[24/May/2023 06:54:05] "GET /static/CIFAR10_model/optimizer.tflite HTTP/1.1" 200 3932
[24/May/2023 06:54:05] "GET /static/CIFAR10_model/bottleneck.tflite HTTP/1.1" 200 532
[24/May/2023 06:54:05] "GET /static/CIFAR10_model/initialize.tflite HTTP/1.1" 200 825124
[24/May/2023 06:54:05] "POST /train/server HTTP/1.1" 200 32
DEBUG flwr 2023-05-24 06:54:09,167 | server.py:218 | fit_round 1: strategy sampled 1 clients (out of 1)
DEBUG flwr 2023-05-24 06:54:48,698 | server.py:232 | fit_round 1 received 1 results and 0 failures
DEBUG flwr 2023-05-24 06:54:48,704 | server.py:168 | evaluate_round 1: strategy sampled 2 clients (out of 2)
DEBUG flwr 2023-05-24 06:54:49,299 | server.py:182 | evaluate_round 1 received 2 results and 0 failures
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sichanghe/AFileFolder/dyn_flower_android_drf/backend/train/run.py", line 79, in flwr_server
    start_server(
  File "/opt/homebrew/lib/python3.11/site-packages/flwr/server/app.py", line 176, in start_server
    hist = _fl(
           ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flwr/server/app.py", line 217, in _fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flwr/server/server.py", line 133, in fit
    res_fed = self.evaluate_round(server_round=current_round, timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flwr/server/server.py", line 194, in evaluate_round
    ] = self.strategy.aggregate_evaluate(server_round, results, failures)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flwr/server/strategy/fedavg_android.py", line 235, in aggregate_evaluate
    loss_aggregated = weighted_loss_avg(
                      ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flwr/server/strategy/aggregate.py", line 98, in weighted_loss_avg
    return sum(weighted_losses) / num_total_evaluation_examples
           ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

**Comment by SichangHe** [comment]
This is caused by rapidly converting multiple client files to Kotlin. We will convert files one by one with close monitoring to avoid this problem.
